version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: productfinder
    ports:
      - "7777:80"
    volumes:
      - .:/var/www/html:cached
    networks:
      - backend
networks:
  backend: